title: Abstract Classroom Notes
description: Lecture notes, math and CS documentation

url: "https://notes.abstractclassroom.com"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: dark
search_enabled: true

logo: "/assets/images/green_logo.png"
logo_width: 150px