title: Abstract Classroom Notes
description: Lecture notes for computer science and mathematics.

url: "https://notes.abstractclassroom.com"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: dark
search_enabled: true

logo: /assets/images/green_horizontal_logo.png
logo_width: 300px

